version: "3.9"
services:
  hysteria:
    image: tobyxdd/hysteria:v2.2.3
    container_name: hysteria2
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./server/:/etc/hysteria/
      - ./tls/:/etc/tls/
    command: ["server", "-c", "/etc/hysteria/config.yaml"]
