apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hysteria
  namespace: hysteria
spec:
  selector:
    matchLabels:
      io.kompose.service: hysteria
  template:
    metadata:
      labels:
        io.kompose.service: hysteria
    spec:
      containers:
        - args:
            - server
            - -c
            - /etc/hysteria/config.yaml
          image: tobyxdd/hysteria:v2.2.4
          env:
            - name: HYSTERIA_LOG_LEVEL
              value: error
            - name: HYSTERIA_DISABLE_UPDATE_CHECK
              value: "1"
          name: hysteria2
          ports:
            - containerPort: 443
              hostPort: 8443
              protocol: UDP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - name: hysteria-config-volume
              readOnly: true
              mountPath: "/etc/hysteria"
            - name: hysteria-tls-volume
              readOnly: true
              mountPath: "/etc/tls"
        - name: udp-ping-pong
          image: juouyang/udp-ping-pong:latest
          args: ["0.0.0.0", "12345", "--silent"]
          ports:
            - containerPort: 12345
              hostPort: 12345
              protocol: UDP
      restartPolicy: Always
      volumes:
        - name: hysteria-config-volume
          secret:
            secretName: hysteria-config
        - name: hysteria-tls-volume
          secret:
            secretName: apps-k8s-juouyang-com-tls
